/notification:
  get:
    tags: [Notification]
    summary: Fetching all notifications with pagination
    security:
      - bearerAuth: []
    parameters:
      - in: query
        name: page
        schema:
          type: integer
          example: 1
        required: false
        description: Page number
      - in: query
        name: limit
        schema:
          type: integer
          example: 10
        required: false
        description: Number of items per page
      - in: query
        name: isRead
        schema:
          type: string
          enum: [true, false, all]
        required: false
        description: Filter by read status
      - in: query
        name: isAdmin
        schema:
          type: boolean
          example: true
        required: false
        description: Filter by admin to get only admin notifications
    responses:
      "200":
        description: Successful response
        content:
          application/json:
            schema:
              NotificationAllResponse:
                type: object
                properties:
                  notification:
                    type: array
                    description: Array of notification objects
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "X2QA"
                        type:
                          type: string
                          example: "info"
                        message:
                          type: string
                          example: "You have a new order"
                        createdAt:
                          type: string
                          format: date-time
                  metadata:
                    type: object
                    properties:
                      total:
                        type: integer
                        example: 10
                      page:
                        type: integer
                        example: 1
                      limit:
                        type: integer
                        example: 10
                      totalPages:
                        type: integer
                        example: 1

/notification/updateAsRead:
  put:
    tags:
      - Notification
    summary: Mark notifications as read (receives an array of IDs)
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: array
            description: Array of hashed notification IDs
            items:
              type: string
    responses:
      "200":
        description: Successful response
