/comment:
  post:
    tags: [Comment Management]
    summary: Create a new comment
    security:
      - bearerAuth: []
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../../openapi/components/schemas.yaml#/CommentInput"
    responses:
      201:
        description: Comment created successfully
        content:
          application/json:
            schema:
              $ref: "../../openapi/components/schemas.yaml#/CommentResponse"
      400:
        description: Invalid input
