openapi: 3.0.0
info:
  title: Germany-Assist APIs Documentation
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: Local server
  - url: /staging/backend/api
    description: Staging server From within the Server it self

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /dispute:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute"
  /dispute/create:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute~1create"
  /dispute/{id}/in-review:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute~1{id}~1in-review"
  /dispute/{id}/resolve:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute~1{id}~1resolve"
  /dispute/{id}/cancel:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute~1{id}~1cancel"
  /dispute/provider/response/{id}:
    $ref: "../modules/disputes/dispute.swagger.yaml#/~1dispute~1provider~1response~1{id}"
  /notification:
    $ref: "../modules/notification/notification.swagger.yaml#/~1notification"
  /notification/updateRead:
    $ref: "../modules/notification/notification.swagger.yaml#/~1notification~1updateRead"
  /notification/markAllAsRead:
    $ref: "../modules/notification/notification.swagger.yaml#/~1notification~1markAllAsRead"
  /user:
    $ref: "../modules/user/user.swagger.yaml#/~1user"
  /user/admin:
    $ref: "../modules/user/user.swagger.yaml#/~1user~1admin"
  /user/rep:
    $ref: "../modules/user/user.swagger.yaml#/~1user~1rep"
  /user/root/rep:
    $ref: "../modules/user/user.swagger.yaml#/~1user~1root~1rep"
  /user/admin/all:
    $ref: "../modules/user/user.swagger.yaml#/~1user~1admin~1all"
  /user/profile/image:
    $ref: "../modules/user/user.swagger.yaml#/~1user~1profile~1image"
  /post/comment:
    $ref: "../modules/comment/comment.swagger.yaml#/~1comment"
  /dashboard/provider/finance:
    $ref: "../modules/dashboard/dashboard.swagger.yaml#/~1dashboard~1provider~1finance"
  /dashboard/admin/services:
    $ref: "../modules/dashboard/dashboard.swagger.yaml#/~1dashboard~1admin~1services"
  /dashboard/admin/finance:
    $ref: "../modules/dashboard/dashboard.swagger.yaml#/~1dashboard~1admin~1finance"
  /meta:
    $ref: "../modules/meta/meta.swagger.yaml#/~1meta"
  /order/pay:
    $ref: "../modules/order/order.swagger.yaml#/~1order~1pay"
  /order/client/checkIfBought/{serviceId}:
    $ref: "../modules/order/order.swagger.yaml#/~1order~1client~1checkIfBought~1{serviceId}"
  /order/serviceProvider/getAll:
    $ref: "../modules/order/order.swagger.yaml#/~1order~1serviceProvider~1getAll"
  /order/client/getAll:
    $ref: "../modules/order/order.swagger.yaml#/~1order~1client~1getAll"
  /order/serviceProvider/close/{orderId}:
    $ref: "../modules/order/order.swagger.yaml#/~1order~1serviceProvider~1close~1{orderId}"
  /post/createNewPost:
    $ref: "../modules/post/post.swagger.yaml#/~1post~1createNewPost"
  /timeline/client/readTimeline/{id}:
    $ref: "../modules/timeline/timeline.swagger.yaml#/~1timeline~1client~1readTimeline~1{id}"
  /timeline/provider/archiveTimeline/{id}:
    $ref: "../modules/timeline/timeline.swagger.yaml#/~1timeline~1provider~1archiveTimeline~1{id}"
  /timeline/provider/createNewTimeline/{serviceId}:
    $ref: "../modules/timeline/timeline.swagger.yaml#/~1timeline~1provider~1createNewTimeline~1{serviceId}"
  /variant/provider/archiveVariant/{id}:
    $ref: "../modules/variant/variant.swagger.yaml#/~1variant~1provider~1archiveVariant~1{id}"
  /variant/provider/createNewVariant:
    $ref: "../modules/variant/variant.swagger.yaml#/~1variant~1provider~1createNewVariant"
  /service:
    $ref: "../modules/service/service.swagger.yaml#/~1service"
  /service/{id}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1{id}"
  /service/provider:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider"
  /service/provider/services:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider~1services"
  /service/provider/services/{id}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider~1services~1{id}"
  /service/provider/services/status:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider~1services~1status"
  /service/provider/services/unpublish/{serviceId}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider~1services~1unpublish~1{serviceId}"
  /service/provider/services/publish/{serviceId}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1provider~1services~1publish~1{serviceId}"
  /service/admin/services:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1admin~1services"
  /service/admin/services/{id}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1admin~1services~1{id}"
  /service/admin/services/{id}/restore:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1admin~1services~1{id}~1restore"
  /service/admin/services/status:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1admin~1services~1status"
  /service/client/favorite/{id}:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1client~1favorite~1{id}"
  /service/client/services:
    $ref: "../modules/service/service.swagger.yaml#/~1service~1client~1services"
  /auth/google:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1google"
  /auth/verifyAccount:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1verifyAccount"
  /auth/login:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1login"
  /auth/profile:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1profile"
  /auth/refresh-token:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1refresh-token"
  /auth/logout:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1logout"
  /auth/admin/verify/{id}:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1admin~1verify~1{id}"
  /auth/changePassword:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1changePassword"
  /auth/password-reset:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1password-reset"
  /auth/password-reset/confirm:
    $ref: "../modules/auth/auth.swagger.yaml#/~1auth~1password-reset~1confirm"
